name: Java Build Check

on:
  push:
    branches:
      - skeleton
  pull_request:
    branches:
      - skeleton

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repository klónozása
        uses: actions/checkout@v4

      - name: Java 18 beállítása
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Java verzió ellenőrzés
        shell: pwsh
        run: javac -version && java -version

      - name: Projekt fordítása
        shell: pwsh
        run: |
          if (Test-Path bin) { Remove-Item -Recurse -Force bin }
          New-Item -ItemType Directory -Path bin
          $SRC_PATH = "MainRepo/skeleton/src"
          javac -d bin (Get-ChildItem -Path "$SRC_PATH/CallTracer" -Recurse -Filter "*.java").FullName
          javac -cp bin (Get-ChildItem -Path "$SRC_PATH/FungoriumClasses" -Recurse -Filter "*.java").FullName
          javac -cp bin -d bin (Get-ChildItem -Path "$SRC_PATH/TestClasses" -Recurse -Filter "*.java").FullName
          javac -cp bin -d bin "$SRC_PATH/Skeleton.java"

      - name: Projekt futtatása
        shell: pwsh
        run: |
          if (Test-Path bin/Skeleton.class) { java -cp bin Skeleton } else { Write-Host "Skeleton class not found"; exit 1 }
