name: Java Build Check

on:
  push:
    branches:
      - skeleton
  pull_request:
    branches:
      - skeleton

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repository klónozása
        uses: actions/checkout@v4

      - name: Java 18 beállítása
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Java verzió ellenőrzés
        shell: cmd
        run: javac -version && java -version

      - name: Projekt fordítása
        shell: cmd
        run: |
          if exist bin rmdir /s /q bin
          mkdir bin
          javac -sourcepath src -d bin src/**/*.java

      - name: Projekt futtatása
        shell: cmd
        run: |
          if exist bin/Skeleton.class (java -cp bin Skeleton) else (echo "Skeleton class not found" && exit /b 1)
