name: Java Build Check

on:
  push:
    branches:
      - skeleton
  pull_request:
    branches:
      - skeleton

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repository klónozása
        uses: actions/checkout@v4

      - name: Java 18 beállítása
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Java verzió ellenőrzés
        shell: cmd
        run: javac -version && java -version

      - name: Projekt fordítása
        shell: cmd
        run: |
          mkdir out
          for /r src %%f in (*.java) do javac -d out %%f

      - name: Tesztfájl futtatása (ha van Main class)
        shell: cmd
        run: |
          if exist out\Skeleton.class (java -cp out Skeleton) else (echo "Main class not found" && exit /b 1)
